In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv(r'/Users/Apple/Downloads/logistic_reg.csv')
df

A       B    C
0   4.5192  2.6487  1.0
1   2.4443  1.5438  1.0
2   4.2409  1.8990  1.0
3   5.8097  2.4711  1.0
4   6.4423  3.3590  1.0
..     ...     ...  ...
95  5.9868  7.3641  0.0
96  4.6711  6.2592  0.0
97  7.5810  8.3703  0.0
98  4.6457  8.5676  0.0
99  4.6457  8.1676  0.0

[100 rows x 3 columns]

In [2]:
y=df['C'].to_numpy().reshape(100,1)
m=df.shape[0]
n=df.shape[1]-1
m,n,y.shape

(100, 2, (100, 1))

In [3]:
#df=df.sample(frac=1)
x1=df['A'].to_numpy()
x2=df['B'].to_numpy()

In [4]:
#calculate mean of x1 and x2
mean1=np.average(x1)
mean2=np.average(x2)
mean1,mean2

(5.14423, 4.866669000000001)

In [5]:
#zero mean 
x1=x1-mean1
x2=x2-mean2
x1,x2

(array([-0.62503, -2.69993, -0.90333,  0.66547,  1.29807,  0.66547,
         1.24747,  1.72827,  1.65237,  3.01877,  2.25957,  2.48737,
         2.61387,  1.42457,  0.21007, -0.67563, -2.16853, -2.69993,
        -4.24343, -3.02883, -1.86483, -0.97923, -0.29603, -1.81423,
         0.00757,  1.12097,  1.12097,  2.05717,  2.51267,  0.99447,
        -0.65033, -0.27073,  0.38717,  0.86787,  2.00657,  2.56327,
         3.17057,  3.37297,  3.60067,  2.71507,  1.85477,  0.36187,
        -0.22013,  1.50047,  2.53797,  2.89217,  3.77787,  2.71507,
         1.44987,  0.89317, -2.42153, -3.20593, -3.45903, -0.82743,
        -1.71303,  0.33657, -1.02983, -1.94083, -1.02983, -0.04303,
        -0.24543,  0.81727,  0.61487,  1.55107,  0.58957,  1.47517,
         2.05717,  2.05717,  3.44887,  2.61387,  2.61387, -0.04303,
        -0.92863, -1.66243, -2.77583, -3.35783, -4.24343, -4.24343,
        -3.18063, -3.73733, -2.72523, -2.26973, -1.13103, -0.47313,
         0.03287,  1.07037,  0.31127,  0.84257, 

In [6]:
#covariance matrix computation
cov1=np.dot(x1,x1.T)
cov2=np.dot(x1,x2.T)
cov3=np.dot(x2,x1.T)
cov4=np.dot(x2,x2.T)
cov1,cov2,cov3,cov4

(438.24007921000003, 84.19793962299998, 84.19793962299998, 382.2067278739)

In [7]:
sigma=(1/(m-1))*np.array([[cov1,cov2],[cov3,cov4]])
sigma

array([[4.42666747, 0.85048424],
       [0.85048424, 3.86067402]])

In [8]:
#eigen values and eigen vectors
e_values,U=np.linalg.eig(sigma)
e_values,U

(array([5.04000248, 3.247339  ]),
 array([[ 0.81108805, -0.58492407],
        [ 0.58492407,  0.81108805]]))

In [9]:
U.shape

(2, 2)

In [10]:
U_reduce=U[0].reshape(2,1)
U_reduce,U_reduce.shape

(array([[ 0.81108805],
        [-0.58492407]]),
 (2, 1))

In [11]:
z=[]
for i in range(len(x1)):
    temp=np.array([x1[i],x2[i]]).reshape(2,1)
    z.append(U_reduce.T.dot(temp))

In [12]:
new_x=np.array(z).reshape(100,1)
new_x.shape,new_x

((100, 1),
 array([[ 0.79038909],
        [-0.2462549 ],
        [ 1.00318086],
        [ 1.94098074],
        [ 1.93472096],
        [ 1.49088167],
        [ 1.62824136],
        [ 1.64894993],
        [ 2.03742893],
        [ 2.52252154],
        [ 2.40299307],
        [ 2.17228736],
        [ 1.61714288],
        [ 1.10255644],
        [ 0.68299459],
        [ 0.53006   ],
        [-0.11530876],
        [-0.08469888],
        [-1.27893977],
        [-0.62842729],
        [ 0.52338575],
        [ 1.13780281],
        [ 1.50727764],
        [-0.25493484],
        [ 0.77260631],
        [ 1.3756057 ],
        [ 1.19100366],
        [ 3.61217208],
        [ 3.4737916 ],
        [ 2.61171878],
        [ 1.49692918],
        [ 1.1008036 ],
        [ 1.35745688],
        [ 1.25115582],
        [ 1.69001521],
        [ 1.81843587],
        [ 2.08019861],
        [ 2.59057939],
        [ 2.60212661],
        [ 2.81859419],
        [ 2.45550869],
        [ 1.44081887],
        [ 1.09569414],


In [13]:
df1 = pd.DataFrame(new_x, columns=['X'])
df1['y']=y
df1

X    y
0   0.790389  1.0
1  -0.246255  1.0
2   1.003181  1.0
3   1.940981  1.0
4   1.934721  1.0
..       ...  ...
95 -0.777409  0.0
96 -1.198275  0.0
97 -0.072923  0.0
98 -2.569115  0.0
99 -2.335146  0.0

[100 rows x 2 columns]

In [14]:
#Decompression
x_approx=U_reduce.dot(new_x.T)
x_approx.T.shape

(100, 2)

In [15]:
x_approx[0]

array([ 0.64107515, -0.19973441,  0.81366801,  1.57430629,  1.56922906,
        1.20923631,  1.32064712,  1.33744359,  1.65253426,  2.04598709,
        1.94903897,  1.76191633,  1.31164527,  0.89427036,  0.55396875,
        0.42992533, -0.09352556, -0.06869825, -1.03733277, -0.50970986,
        0.42451193,  0.92285827,  1.22253489, -0.2067746 ,  0.62665175,
        1.11573735,  0.96600884,  2.92978962,  2.81755087,  2.1183339 ,
        1.21414138,  0.89284865,  1.10101706,  1.01479754,  1.37075114,
        1.47491161,  1.68722424,  2.10118799,  2.11055381,  2.28612807,
        1.99163376,  1.16863097,  0.88870443,  1.47774049,  1.82329019,
        1.46664282,  1.68424283,  1.60286129,  0.77987815,  0.63828556,
       -1.45807782, -1.53417197, -1.38243307, -0.33451283, -0.5988728 ,
        0.02873856, -0.66421872, -1.06697842, -0.92629105, -0.60474887,
       -0.49452053, -0.21660308, -0.13450813,  0.11636145, -0.46000271,
       -0.11143232,  0.09362996,  0.42122038,  0.96235332,  0.61

In [16]:
#Average Squared Projection Error
sum=0
for i in range(len(x_approx)):
    sum+=(x_approx[0][i]-x1[i])**2
    sum+=(x_approx[1][i]-x2[i])**2
error=sum/m

In [17]:
print("AVERAGE SQUARED PROJECTION ERROR :",error)

AVERAGE SQUARED PROJECTION ERROR : 0.22955772988085865
